on: [push]

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload Files
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.APP_HOST }}
          port: 22
          username: ${{ secrets.APP_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          localPath: '//index.html'
          remotePath: '/'